set_attack_value(49, AG_CATEGORY, 2);
set_attack_value(49, AG_SPRITE, sprite_get("finalsmash"));
set_attack_value(49, AG_NUM_WINDOWS, 6);
set_attack_value(49, AG_HURTBOX_SPRITE, asset_get("ex_guy_hurt_box"));

set_window_value(49, 1, AG_WINDOW_TYPE, 0);
set_window_value(49, 1, AG_WINDOW_LENGTH, 6);
set_window_value(49, 1, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 2, AG_WINDOW_VSPEED, 0);
set_window_value(49, 1, AG_WINDOW_HSPEED_TYPE, 1);
set_window_value(49, 1, AG_WINDOW_VSPEED_TYPE, 1);

set_window_value(49, 2, AG_WINDOW_TYPE, 0);
set_window_value(49, 2, AG_WINDOW_LENGTH, 20);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 2, AG_WINDOW_ANIM_FRAME_START, 1);
set_window_value(49, 2, AG_WINDOW_VSPEED, -50);
set_window_value(49, 2, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 2, AG_WINDOW_SFX, asset_get("sfx_jumpground"));

set_window_value(49, 3, AG_WINDOW_TYPE, 0);
set_window_value(49, 3, AG_WINDOW_LENGTH, 5);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 3, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(49, 3, AG_WINDOW_VSPEED, 20);
set_window_value(49, 3, AG_WINDOW_VSPEED_TYPE, 1);
set_window_value(49, 3, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 3, AG_WINDOW_SFX, sound_get("fox_final"));

set_window_value(49, 4, AG_WINDOW_TYPE, 0);
set_window_value(49, 4, AG_WINDOW_LENGTH, 20);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 4, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(49, 4, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 4, AG_WINDOW_SFX, asset_get("sfx_shovel_hit_heavy2"));

set_window_value(49, 5, AG_WINDOW_TYPE, 0);
set_window_value(49, 5, AG_WINDOW_LENGTH, 8);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(49, 5, AG_WINDOW_ANIM_FRAME_START, 3);

set_window_value(49, 6, AG_WINDOW_TYPE, 0);
set_window_value(49, 6, AG_WINDOW_LENGTH, 1);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(49, 6, AG_WINDOW_ANIM_FRAME_START, 2);
set_window_value(49, 6, AG_WINDOW_HAS_SFX, 1);
set_window_value(49, 6, AG_WINDOW_SFX, asset_get("sfx_abyss_explosion"));

set_num_hitboxes(49, 6);

set_hitbox_value(49, 1, HG_PARENT_HITBOX, 1);
set_hitbox_value(49, 1, HG_HITBOX_TYPE, 1 );
set_hitbox_value(49, 1, HG_WINDOW, 1);
set_hitbox_value(49, 1, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(49, 1, HG_LIFETIME, 3);
set_hitbox_value(49, 1, HG_WIDTH, 100);
set_hitbox_value(49, 1, HG_HEIGHT, 80);
set_hitbox_value(49, 1, HG_HITBOX_X, 21);
set_hitbox_value(49, 1, HG_HITBOX_Y, -28);
set_hitbox_value(49, 1, HG_SHAPE, 1 );
set_hitbox_value(49, 1, HG_PRIORITY, 10 );
set_hitbox_value(49, 1, HG_DAMAGE, 0);
set_hitbox_value(49, 1, HG_ANGLE, 361);
set_hitbox_value(49, 1, HG_BASE_KNOCKBACK, 1);
set_hitbox_value(49, 1, HG_KNOCKBACK_SCALING, 0.1);
set_hitbox_value(49, 1, HG_BASE_HITPAUSE, 0);
set_hitbox_value(49, 1, HG_EXTRA_HITPAUSE, 100);
set_hitbox_value(49, 1, HG_ANGLE_FLIPPER, 6 );
set_hitbox_value(49, 1, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 1, HG_EXTRA_CAMERA_SHAKE, 1 );

set_hitbox_value(49, 2, HG_PARENT_HITBOX, 2);
set_hitbox_value(49, 2, HG_HITBOX_TYPE, 1 );
set_hitbox_value(49, 2, HG_WINDOW, 3);
set_hitbox_value(49, 2, HG_WINDOW_CREATION_FRAME, 2);
set_hitbox_value(49, 2, HG_LIFETIME, 3);
set_hitbox_value(49, 2, HG_WIDTH, 374);
set_hitbox_value(49, 2, HG_HEIGHT, 212);
set_hitbox_value(49, 2, HG_HITBOX_X, 0);
set_hitbox_value(49, 2, HG_HITBOX_Y, -92);
set_hitbox_value(49, 2, HG_SHAPE, 1 );
set_hitbox_value(49, 2, HG_PRIORITY, 10 );
set_hitbox_value(49, 2, HG_DAMAGE, 10);
set_hitbox_value(49, 2, HG_ANGLE, 270);
set_hitbox_value(49, 2, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(49, 2, HG_KNOCKBACK_SCALING, 0.5);
set_hitbox_value(49, 2, HG_BASE_HITPAUSE, 20);
set_hitbox_value(49, 2, HG_ANGLE_FLIPPER, 6 );
set_hitbox_value(49, 2, HG_TECHABLE, 1 );
set_hitbox_value(49, 2, HG_HITBOX_GROUP, 2);
set_hitbox_value(49, 2, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(49, 2, HG_EXTRA_CAMERA_SHAKE, 1 );

set_hitbox_value(49, 3, HG_PARENT_HITBOX, 3);
set_hitbox_value(49, 3, HG_HITBOX_TYPE, 1 );
set_hitbox_value(49, 3, HG_WINDOW, 4);
set_hitbox_value(49, 3, HG_WINDOW_CREATION_FRAME, 1);
set_hitbox_value(49, 3, HG_LIFETIME, 3);
set_hitbox_value(49, 3, HG_WIDTH, 374);
set_hitbox_value(49, 3, HG_HEIGHT, 212);
set_hitbox_value(49, 3, HG_HITBOX_X, 0);
set_hitbox_value(49, 3, HG_HITBOX_Y, -92);
set_hitbox_value(49, 3, HG_SHAPE, 1 );
set_hitbox_value(49, 3, HG_PRIORITY, 10 );
set_hitbox_value(49, 3, HG_DAMAGE, 10);
set_hitbox_value(49, 3, HG_ANGLE, 361);
set_hitbox_value(49, 3, HG_BASE_KNOCKBACK, 12);
set_hitbox_value(49, 3, HG_KNOCKBACK_SCALING, 1.3);
set_hitbox_value(49, 3, HG_BASE_HITPAUSE, 10);
set_hitbox_value(49, 3, HG_HITPAUSE_SCALING, 1);
set_hitbox_value(49, 3, HG_EXTRA_HITPAUSE, 25);
set_hitbox_value(49, 3, HG_ANGLE_FLIPPER, 3 );
set_hitbox_value(49, 3, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 3, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(49, 3, HG_EXTRA_CAMERA_SHAKE, 1 );

set_hitbox_value(49, 4, HG_PARENT_HITBOX, 4);
set_hitbox_value(49, 4, HG_HITBOX_TYPE, 1 );
set_hitbox_value(49, 4, HG_WINDOW, 5);
set_hitbox_value(49, 4, HG_WINDOW_CREATION_FRAME, 3);
set_hitbox_value(49, 4, HG_LIFETIME, 3);
set_hitbox_value(49, 4, HG_WIDTH, 374);
set_hitbox_value(49, 4, HG_HEIGHT, 212);
set_hitbox_value(49, 4, HG_HITBOX_X, 0);
set_hitbox_value(49, 4, HG_HITBOX_Y, -92);
set_hitbox_value(49, 4, HG_SHAPE, 1 );
set_hitbox_value(49, 4, HG_PRIORITY, 10 );
set_hitbox_value(49, 4, HG_DAMAGE, 2);
set_hitbox_value(49, 4, HG_ANGLE, 361);
set_hitbox_value(49, 4, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(49, 4, HG_KNOCKBACK_SCALING, 0.1);
set_hitbox_value(49, 4, HG_BASE_HITPAUSE, 2);
set_hitbox_value(49, 4, HG_EXTRA_HITPAUSE, 10);
set_hitbox_value(49, 4, HG_ANGLE_FLIPPER, 6 );
set_hitbox_value(49, 4, HG_HITBOX_GROUP, -1);
set_hitbox_value(49, 4, HG_HIT_SFX, asset_get("sfx_blow_heavy1"));
set_hitbox_value(49, 4, HG_EXTRA_CAMERA_SHAKE, 1 );
set_hitbox_value(49, 4, HG_SDI_MULTIPLIER, 0 );

set_hitbox_value(49, 5, HG_PARENT_HITBOX, 4);
set_hitbox_value(49, 5, HG_HITBOX_TYPE, 1 );
set_hitbox_value(49, 5, HG_WINDOW, 5);
set_hitbox_value(49, 5, HG_WINDOW_CREATION_FRAME, 7);
set_hitbox_value(49, 5, HG_LIFETIME, 3);
set_hitbox_value(49, 5, HG_HITBOX_X, 0);
set_hitbox_value(49, 5, HG_HITBOX_Y, -92);
set_hitbox_value(49, 5, HG_HITBOX_GROUP, -1);

set_hitbox_value(49, 6, HG_PARENT_HITBOX, 3);
set_hitbox_value(49, 6, HG_HITBOX_TYPE, 1 );
set_hitbox_value(49, 6, HG_WINDOW, 6);
set_hitbox_value(49, 6, HG_LIFETIME, 3);
set_hitbox_value(49, 6, HG_HITBOX_X, 0);
set_hitbox_value(49, 6, HG_HITBOX_Y, -92);
set_hitbox_value(49, 6, HG_HITBOX_GROUP, -1);
